package edu.shamalov.os

const val MIN_WAITING_MILLIS = 100L
const val MAX_WAITING_MILLIS = 200L
val WAITING_MILLIS_RANGE = (MIN_WAITING_MILLIS..MAX_WAITING_MILLIS)

const val MIN_RUNNING_MILLIS = 100L
const val MAX_RUNNING_MILLIS = 200L
val RUNNING_MILLIS_RANGE = (MIN_RUNNING_MILLIS..MAX_RUNNING_MILLIS)

const val ACCELERATION_COEFFICIENT = 1.0


